name: CI

on:
  push:
    branches: [ "main", "LabWork5" ]
  pull_request:
    branches: [ "main", "LabWork5" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build containers
        run: docker compose build

      - name: Start containers
        run: docker compose up -d

      - name: Wait for API
        run: |
          for i in {1..20}; do
            if curl -f http://localhost:8080/health; then
              exit 0
            fi
            sleep 3
          done
          exit 1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install test dependencies
        run: pip install requests pytest

      - name: Run integration tests
        run: pytest tests/test_api.py

      - name: Show logs on failure
        if: failure()
        run: docker compose logs

      - name: Stop containers
        if: always()
        run: docker compose down